### ISSUE TITLE
Error GTF format (line 7)

### ISSUE THREAD

**Issue by ge2sasag** [danilotat/UTR_to_GTF#1]
Hi! 

I have the same annotation problem since I'm analyzing 3'RNAseq data and I would like to try with your script. I formated the GTF file as indicated to change the space for = and run the following command:

`python utr_add_extend.py --input edited.gtf --output extended.gtf`

But I got this error:

```
 File "utr_add_extend.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

```
I'm not sure about the meaning of "Must be a fw only version of a valid GTF". 

After the space/= conversion, my GTF file looks like this:

```
chr1    HAVANA  gene    3073253 3074322 .       +       .       gene_id="ENSMUSG00000102693.1";=gene_type="TEC";=gene_name="4933401J01Rik";=level=2;=mgi_id="MGI:1918292";=havana_gene="OTTMUSG00000049935.1";
chr1    HAVANA  transcript      3073253 3074322 .       +       .       gene_id="ENSMUSG00000102693.1";=transcript_id="ENSMUST00000193812.1";=gene_type="TEC";=gene_name="4933401J01Rik";=transcript_type="TEC";=transcript_name="4933401J01Rik-201";=level=2;=transcript_support_level="NA";=mgi_id="MGI:1918292";=tag="basic";=havana_gene="OTTMUSG00000049935.1";=havana_transcript="OTTMUST00000127109.1";
chr1    HAVANA  exon    3073253 3074322 .       +       .       gene_id="ENSMUSG00000102693.1";=transcript_id="ENSMUST00000193812.1";=gene_type="TEC";=gene_name="4933401J01Rik";=transcript_type="TEC";=transcript_name="4933401J01Rik-201";=exon_number=1;=exon_id="ENSMUSE00001343744.1";=level=2;=transcript_support_level="NA";=mgi_id="MGI:1918292";=tag="basic";=havana_gene="OTTMUSG00000049935.1";=havana_transcript="OTTMUST00000127109.1";
chr1    ENSEMBL gene    3102016 3102125 .       +       .       gene_id="ENSMUSG00000064842.1";=gene_type="snRNA";=gene_name="Gm26206";=level=3;=mgi_id="MGI:5455983";
chr1    ENSEMBL transcript      3102016 3102125 .       +       .       gene_id="ENSMUSG00000064842.1";=transcript_id="ENSMUST00000082908.1";=gene_type="snRNA";=gene_name="Gm26206";=transcript_type="snRNA";=transcript_name="Gm26206-201";=level=3;=transcript_support_level="NA";=mgi_id="MGI:5455983";=tag="basic";
chr1    ENSEMBL exon    3102016 3102125 .       +       .       gene_id="ENSMUSG00000064842.1";=transcript_id="ENSMUST00000082908.1";=gene_type="snRNA";=gene_name="Gm26206";=transcript_type="snRNA";=transcript_name="Gm26206-201";=exon_number=1;=exon_id="ENSMUSE00000522066.1";=level=3;=transcript_support_level="NA";=mgi_id="MGI:5455983";=tag="basic";
chr1    HAVANA  gene    3205901 3671498 .       -       .       gene_id="ENSMUSG00000051951.5";=gene_type="protein_coding";=gene_name="Xkr4";=level=2;=mgi_id="MGI:3528744";=havana_gene="OTTMUSG00000026353.2";

```

Thank you very much in advance!
Gema

**Comment by danilotat** [comment]
Hi,

Please note that this is in development and I'm working to push some updates to fix the way in which 3'UTR features were added & extended: actually you may find some UTR regions overlapping the CDS of the latest exons.

I've changed something so there's no more need to convert the GTF file: it could be used as it is. 

Your error is due to an HTML tag you've got into the Python file: it's related to the way you're copying the script. Take it from RAW (https://raw.githubusercontent.com/danilotat/UTR_to_GTF/master/utr_add_extend.py) to be sure you're not pasting anything else, or download as zip.

Cheers,
Danilo

**Comment by ge2sasag** [comment]
Hi! 

Yes, it was my fault, I downloaded the wrong thing. I run it without editing the GTF file and I got this:

```
Malformed file.
This line isn't good. ['gene_id "ENSMUSG00000102693.1"', ' gene_type "TEC"', ' gene_name "4933401J01Rik"', ' level 2', ' mgi_id "MGI:1918292"', ' hava
na_gene "OTTMUSG00000049935.1"']

```

The GTF file I'm using is `gencode.vM25.annotation.gtf` 
Is there any specific annotation that works best with your script? 

Thank you very much for your help, I can't find a solution for this and your script looks very useful.
Gema

**Comment by danilotat** [comment]
As said in the README, it was designed to work with an Ensembl GTF. A Gencode GTF carries some differences which could lead to errors: in your case, an attribute could appear as:

`level 2`

So, without quotes, it won't be captured by the script's function designed to parse the 9th column (which contains the attributes). Ensembl by default uses quotes to define the value of each field.

**Comment by ge2sasag** [comment]
Ok thank you!

**Comment by ge2sasag** [comment]
Update: it runs smoothly using `Mus_musculus.GRCm38.102.gtf` so I'm closing this. Thanks again!

**Comment by danilotat** [comment]
Inside our team we're working on a pipeline to re-annotate 3' terminus completely from a 3'RNAseq dataset. Shoot me an email if you wanna be updated about the project and/or would test it against your data.
danilotatoni[at]gmail[dot]com

Cheers,
Danilo

**Comment by ge2sasag** [comment]
That would be awesome! Thanks!
